array

In [ ]:
import numpy as np

1D array

In [ ]:
a=np.array((1,2,4,))
print(a)

[1 2 4]


2d array

In [ ]:
b=np.array([[1,2,3],[4,6,7]])
print(b)

[[1 2 3]
 [4 6 7]]


3d array

In [ ]:
c=np.array([[[1,2,3],[4,6,7],[85,35,6]]])
print(c)

[[[ 1  2  3]
  [ 4  6  7]
  [85 35  6]]]


dimensions

In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


ones

In [ ]:
d=np.ones((2,3,2))
print(d)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
j=np.eye(4)
print(j)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
l=np.zeros((3,4))
print(l)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
h=np.arange(3,31,3)
print(h)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
h=np.arange(3,31,3).reshape(5,2)
print(h)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
v=np.linspace(12,24,10)
print(v)

[12.         13.33333333 14.66666667 16.         17.33333333 18.66666667
 20.         21.33333333 22.66666667 24.        ]


In [ ]:
L=np.arange(1,7).reshape(2,3)
print(L)
R=np.arange(9,15).reshape(2,3)
print(R)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
print(L+R)

[[10 12 14]
 [16 18 20]]


In [ ]:
G=np.sum((L,R))
print(G)

90


In [ ]:
g=np.sum((L,R),axis=0)
print(g)

[[10 12 14]
 [16 18 20]]


In [ ]:
g=np.sum((L,R),axis=1)
print(g)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
print(a*b)

[[2 0]
 [0 4]]


In [ ]:
print(a@b)

[[5 4]
 [3 4]]


b=np.array[25,289,361,81]find square roots amd iterate through result values output 5 square isn 25


In [ ]:
s

In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print(np.sqrt(i),"square of",i)


5.0 square of 25
17.0 square of 289
19.0 square of 361
9.0 square of 81


In [ ]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b)))
print("\n")
print(np.hstack((a,b)))

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [50]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("\n")
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
